### PR TITLE
Call auto-subscription to topics for subscribers that implement it

### PR DESCRIPTION
**Pull request by vovimayhem**
## What does this PR do?

Implements the plumbing that would enable subscribers to automatically create a subscription to a topic, if the Subscriber class implements how to do it.

This feature would be required for #17

### CODE REVIEW

**Comment by vovimayhem** [comment]
I'll need to add a couple tests for this change, and add the documentation to use this.

**Comment by vovimayhem** [comment]
OH! I see the documentation is actually on a Github Wiki... I'll post an example of how to implement an `auto_subscribe` method, so it can get included in the Wiki.

**Comment by vovimayhem** [comment]
This is a simple example of how to implement the "Auto-subscribe" method. Of course, you might implement some more complex logic if you need it:

```ruby
class MyAutoSubscriber
  include Subserver::Subscriber
  subserver_options queue: 'default'

  def self.auto_subscribe
    client = Subserver::Pubsub.client
    client.topic('my-topic-name').tap do |topic|
      topic.subscription('my-topic-subscription-name') ||
      topic.subscribe('my-topic-subscription-name')
    end
  end
```

**Comment by vovimayhem** [comment]
@wintheday Take a look at this :)

**Comment by wintheday** [comment]
@vovimayhem  Sorry it took a while to look at this.  It looks great!

**Pull request merged**
